# Generated by Django 5.2 on 2025-05-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('WorkTime', models.IntegerField(verbose_name='Время выполнения (мин)')),
                ('QuestionsCount', models.IntegerField()),
                ('test_result', models.TextField(max_length=20)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=300)),
                ('IsRight', models.BooleanField()),
                ('QuestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.question')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.test'),
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=300, verbose_name='ФИО')),
                ('DateTime', models.DateTimeField(auto_now_add=True, verbose_name='Время завершения')),
                ('Rating', models.FloatField(verbose_name='Проценты')),
                ('ProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.test')),
            ],
            options={
                'verbose_name': 'user_test',
                'verbose_name_plural': 'user_tests',
            },
        ),
    ]
