# Generated by Django 5.2 on 2025-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_alter_test_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='UserName',
            field=models.CharField(max_length=300, verbose_name='Имя пользователя'),
        ),
    ]
